### ISSUE TITLE
With 0.4.1, NULL embedding field being validated even when NULLABLE

### ISSUE THREAD

**Issue by sg650** [ankane/neighbor#24]
Rails 7.2.1
Postgres 15 (pg_vector)

On neighbor `0.4.0` when creating a record with an embedding if `nil` it works - SUCCESS:

```
>> ResearchArticleContent.create!(content: 'CONTENT', content_type: 'CONTENT', research_article_id: 1, embedding: nil)

=> #<ResearchArticleContent:0x000000013ee567f0 id: 5259, research_article_id: 1, content: "CONTENT", ordinal: nil, content_type: "CONTENT", created_at: "2024-08-27 15:07:51.720616000 +0000", updated_at: "2024-08-27 15:07:51.720616000 +0000", embedding: nil, embedding_generated_at: nil>
```

On neighbor `0.4.1` when creating a record with an embedding if `nil` it fails - FAILURE:

```
>> ResearchArticleContent.create!(content: 'CONTENT', content_type: 'CONTENT', research_article_id: 1, embedding: nil)

/Users/steve/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/lib/irb.rb:1285:in `full_message': PG::DataException: ERROR:  vector must have at least 1 dimension (ActiveRecord::StatementInvalid)
CONTEXT:  unnamed portal parameter $7 = '...'

/Users/steve/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/activerecord-7.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params': ERROR:  vector must have at least 1 dimension (PG::DataException)
CONTEXT:  unnamed portal parameter $7 = '...'
```

Table Schema:

```ruby
  create_table "research_article_contents", force: :cascade do |t|
    t.text "content"
    t.string "content_type"
    t.datetime "created_at", null: false
    t.vector "embedding", limit: 1536
    t.datetime "embedding_generated_at"
    t.integer "ordinal"
    t.bigint "research_article_id", null: false
    t.datetime "updated_at", null: false
    t.index ["research_article_id"], name: "index_research_article_contents_on_research_article_id"
  end
  ```

**Comment by ankane** [comment]
Thanks @sg650, just pushed 0.4.2 with a fix.
